version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/" # Location of package manifests
      schedule:
          interval: "monthly"
      allow:
          - dependency-name: "@node-steam/vdf"
          - dependency-name: "vdf-parser"
          - dependency-name: "kvparser"
